openapi: 3.1.0

info:
  title: F1 Telemetry API
  description: API for querying F1 telemetry using PromQL
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
paths:
  /query/range:
    post:
      summary: Perform a range query
      responses:
        '200':
          description: Query result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    description: All series the query resulted in
                    items:
                      $ref: '#/components/schemas/Series'
  /labels:
    get:
      summary: Retrieve all label names.
      parameters:
        - in: query
          name: from
          schema:
            type: string
          required: true
          description: Session time at which to start retrieving labels
          example: 0s
        - in: query
          name: to
          schema:
            type: string
          required: true
          description: Session time at which to stop retrieving labels
          example: 1m10s
      responses:
        '200':
          description: Label names
          content:
            application/json:
              schema:
                type: object
                properties:
                  warnings:
                  labels:
                    items:
                      type: string
  /labels/{name}:
    get:
      summary: Retrieve all values for a specific label
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: Name of the label for which to retreive values
          example: session
        - in: query
          name: from
          schema:
            type: string
          required: true
          description: Session time at which to start retrieving labels
          example: 0s
        - in: query
          name: to
          schema:
            type: string
          required: true
          description: Session time at which to stop retrieving labels
          example: 1m10s
      responses:
        '200':
          description: Label values for the given name
          content:
            application/json:
              schema:
                type: object
                properties:
                  warnings:
                  values:
                    items:
                      type: string
  /sessions:
    get:
      summary: Retrieve all sessions
      responses:
        '200':
          description: Retrieved sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Session'

components:
  schemas:
    RangeQuery:
      type: object
      required:
        - query
        - from
        - to
      properties:
        query:
          type: string
          description: PromQL query to execute
        from:
          type: string
          description: Session time at which to start querying data
          example: 5m10s
        to:
          type: string
          description: Session time at which to stop querying data
          example: 10m
        interval:
          type: string
          description: Interval between data points
          example: 1s
          default: 10ms
        maxSamples:
          type: number
          description: Maximum number of samples to allow the query to return
          default: 1000
    Series:
      type: object
      required:
        - metrics
        - values
      properties:
        metrics:
          type: object
          additionalProperties:
            type: string
        values:
          $ref: '#/components/schemas/Point'
    Point:
      type: array
      prefixItems:
        - type: number
          description: Session time the value was recorded
        - type: string
          description: Value
    Session:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: ID of the session
        type:
          type: string
          description: Type of session
          enum:
            - OneShotQualifying
            - Race
            - TimeTrial
        game:
          type: string
          description: Game version
        track:
          type: string
          description: The track the session took place on
