// Code generated by "stringer -type=Driver"; DO NOT EDIT.

package f12021

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DriverNetworkHuman-255]
	_ = x[DriverCarlosSainz-0]
	_ = x[DriverDaniilKvyat-1]
	_ = x[DriverDanielRicciardo-2]
	_ = x[DriverFernandoAlonso-3]
	_ = x[DriverFelipeMassa-4]
	_ = x[DriverKimiRäikkönen-6]
	_ = x[DriverLewisHamilton-7]
	_ = x[DriverMaxVerstappen-9]
	_ = x[DriverNicoHulkenburg-10]
	_ = x[DriverKevinMagnussen-11]
	_ = x[DriverRomainGrosjean-12]
	_ = x[DriverSebastianVettel-13]
	_ = x[DriverSergioPerez-14]
	_ = x[DriverValtteriBottas-15]
	_ = x[DriverEstebanOcon-17]
	_ = x[DriverLanceStroll-19]
	_ = x[DriverArronBarnes-20]
	_ = x[DriverMartinGiles-21]
	_ = x[DriverAlexMurray-22]
	_ = x[DriverLucasRoth-23]
	_ = x[DriverIgorCorreia-24]
	_ = x[DriverSophieLevasseur-25]
	_ = x[DriverJonasSchiffer-26]
	_ = x[DriverAlainForest-27]
	_ = x[DriverJayLetourneau-28]
	_ = x[DriverEstoSaari-29]
	_ = x[DriverYasarAtiyeh-30]
	_ = x[DriverCallistoCalabresi-31]
	_ = x[DriverNaotaIzum-32]
	_ = x[DriverHowardClarke-33]
	_ = x[DriverWilheimKaufmann-34]
	_ = x[DriverSantiagoMoreno-39]
	_ = x[DriverBenjaminCoppens-40]
	_ = x[DriverNoahVisser-41]
	_ = x[DriverGertWaldmuller-42]
	_ = x[DriverJulianQuesada-43]
	_ = x[DriverDanielJones-44]
	_ = x[DriverArtemMarkelov-45]
	_ = x[DriverTadasukeMakino-46]
	_ = x[DriverSeanGelael-47]
	_ = x[DriverNyckDeVries-48]
	_ = x[DriverJackAitken-49]
	_ = x[DriverGeorgeRussell-50]
	_ = x[DriverMaximilianGünther-51]
	_ = x[DriverNireiFukuzumi-52]
	_ = x[DriverLucaGhiotto-53]
	_ = x[DriverLandoNorris-54]
	_ = x[DriverSérgioSetteCâmara-55]
	_ = x[DriverLouisDelétraz-56]
	_ = x[DriverAntonioFuoco-57]
	_ = x[DriverCharlesLeclerc-58]
	_ = x[DriverPierreGasly-59]
	_ = x[DriverAlexanderAlbon-62]
	_ = x[DriverNicholasLatifi-63]
	_ = x[DriverDorianBoccolacci-64]
	_ = x[DriverNikoKari-65]
	_ = x[DriverRobertoMerhi-66]
	_ = x[DriverArjunMaini-67]
	_ = x[DriverAlessioLorandi-68]
	_ = x[DriverRubenMeijer-69]
	_ = x[DriverRashidNair-70]
	_ = x[DriverJackTremblay-71]
	_ = x[DriverAlainProst-76]
	_ = x[DriverAyrtonSenna-77]
	_ = x[DriverNobuharuMatsushita-78]
	_ = x[DriverNikitaMazepin-79]
	_ = x[DriverGuanyaZhou-80]
	_ = x[DriverMickSchumacher-81]
	_ = x[DriverCallumIlott-82]
	_ = x[DriverJuanManuelCorrea-83]
	_ = x[DriverJordanKing-84]
	_ = x[DriverMahaveerRaghunathan-85]
	_ = x[DriverTatianaCalderon-86]
	_ = x[DriverAnthoineHubert-87]
	_ = x[DriverGuilianoAlesi-88]
	_ = x[DriverRalphBoschung-89]
	_ = x[DriverMichaelSchumacher-90]
	_ = x[DriverDanTicktum-91]
	_ = x[DriverMarcusArmstrong-92]
	_ = x[DriverChristianLundgaard-93]
	_ = x[DriverYukiTsunoda-94]
	_ = x[DriverJehanDaruvala-95]
	_ = x[DriverGulhermeSamaia-96]
	_ = x[DriverPedroPiquet-97]
	_ = x[DriverFelipeDrugovich-98]
	_ = x[DriverRobertSchwartzman-99]
	_ = x[DriverRoyNissany-100]
	_ = x[DriverMarinoSato-101]
	_ = x[DriverAidanJackson-102]
	_ = x[DriverCasperAkkerman-103]
	_ = x[DriverJensonButton-109]
	_ = x[DriverDavidCoulthard-110]
	_ = x[DriverNicoRosberg-111]
}

const (
	_Driver_name_0 = "DriverCarlosSainzDriverDaniilKvyatDriverDanielRicciardoDriverFernandoAlonsoDriverFelipeMassa"
	_Driver_name_1 = "DriverKimiRäikkönenDriverLewisHamilton"
	_Driver_name_2 = "DriverMaxVerstappenDriverNicoHulkenburgDriverKevinMagnussenDriverRomainGrosjeanDriverSebastianVettelDriverSergioPerezDriverValtteriBottas"
	_Driver_name_3 = "DriverEstebanOcon"
	_Driver_name_4 = "DriverLanceStrollDriverArronBarnesDriverMartinGilesDriverAlexMurrayDriverLucasRothDriverIgorCorreiaDriverSophieLevasseurDriverJonasSchifferDriverAlainForestDriverJayLetourneauDriverEstoSaariDriverYasarAtiyehDriverCallistoCalabresiDriverNaotaIzumDriverHowardClarkeDriverWilheimKaufmann"
	_Driver_name_5 = "DriverSantiagoMorenoDriverBenjaminCoppensDriverNoahVisserDriverGertWaldmullerDriverJulianQuesadaDriverDanielJonesDriverArtemMarkelovDriverTadasukeMakinoDriverSeanGelaelDriverNyckDeVriesDriverJackAitkenDriverGeorgeRussellDriverMaximilianGüntherDriverNireiFukuzumiDriverLucaGhiottoDriverLandoNorrisDriverSérgioSetteCâmaraDriverLouisDelétrazDriverAntonioFuocoDriverCharlesLeclercDriverPierreGasly"
	_Driver_name_6 = "DriverAlexanderAlbonDriverNicholasLatifiDriverDorianBoccolacciDriverNikoKariDriverRobertoMerhiDriverArjunMainiDriverAlessioLorandiDriverRubenMeijerDriverRashidNairDriverJackTremblay"
	_Driver_name_7 = "DriverAlainProstDriverAyrtonSennaDriverNobuharuMatsushitaDriverNikitaMazepinDriverGuanyaZhouDriverMickSchumacherDriverCallumIlottDriverJuanManuelCorreaDriverJordanKingDriverMahaveerRaghunathanDriverTatianaCalderonDriverAnthoineHubertDriverGuilianoAlesiDriverRalphBoschungDriverMichaelSchumacherDriverDanTicktumDriverMarcusArmstrongDriverChristianLundgaardDriverYukiTsunodaDriverJehanDaruvalaDriverGulhermeSamaiaDriverPedroPiquetDriverFelipeDrugovichDriverRobertSchwartzmanDriverRoyNissanyDriverMarinoSatoDriverAidanJacksonDriverCasperAkkerman"
	_Driver_name_8 = "DriverJensonButtonDriverDavidCoulthardDriverNicoRosberg"
	_Driver_name_9 = "DriverNetworkHuman"
)

var (
	_Driver_index_0 = [...]uint8{0, 17, 34, 55, 75, 92}
	_Driver_index_1 = [...]uint8{0, 21, 40}
	_Driver_index_2 = [...]uint8{0, 19, 39, 59, 79, 100, 117, 137}
	_Driver_index_4 = [...]uint16{0, 17, 34, 51, 67, 82, 99, 120, 139, 156, 175, 190, 207, 230, 245, 263, 284}
	_Driver_index_5 = [...]uint16{0, 20, 41, 57, 77, 96, 113, 132, 152, 168, 185, 201, 220, 244, 263, 280, 297, 322, 342, 360, 380, 397}
	_Driver_index_6 = [...]uint8{0, 20, 40, 62, 76, 94, 110, 130, 147, 163, 181}
	_Driver_index_7 = [...]uint16{0, 16, 33, 57, 76, 92, 112, 129, 151, 167, 192, 213, 233, 252, 271, 294, 310, 331, 355, 372, 391, 411, 428, 449, 472, 488, 504, 522, 542}
	_Driver_index_8 = [...]uint8{0, 18, 38, 55}
)

func (i Driver) String() string {
	switch {
	case i <= 4:
		return _Driver_name_0[_Driver_index_0[i]:_Driver_index_0[i+1]]
	case 6 <= i && i <= 7:
		i -= 6
		return _Driver_name_1[_Driver_index_1[i]:_Driver_index_1[i+1]]
	case 9 <= i && i <= 15:
		i -= 9
		return _Driver_name_2[_Driver_index_2[i]:_Driver_index_2[i+1]]
	case i == 17:
		return _Driver_name_3
	case 19 <= i && i <= 34:
		i -= 19
		return _Driver_name_4[_Driver_index_4[i]:_Driver_index_4[i+1]]
	case 39 <= i && i <= 59:
		i -= 39
		return _Driver_name_5[_Driver_index_5[i]:_Driver_index_5[i+1]]
	case 62 <= i && i <= 71:
		i -= 62
		return _Driver_name_6[_Driver_index_6[i]:_Driver_index_6[i+1]]
	case 76 <= i && i <= 103:
		i -= 76
		return _Driver_name_7[_Driver_index_7[i]:_Driver_index_7[i+1]]
	case 109 <= i && i <= 111:
		i -= 109
		return _Driver_name_8[_Driver_index_8[i]:_Driver_index_8[i+1]]
	case i == 255:
		return _Driver_name_9
	default:
		return "Driver(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
