// Code generated by "stringer -type=Nationality"; DO NOT EDIT.

package f12021

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NationalityUnknown-0]
	_ = x[NationalityAmerican-1]
	_ = x[NationalityArgentinean-2]
	_ = x[NationalityAustralian-3]
	_ = x[NationalityAustrian-4]
	_ = x[NationalityAzerbaijani-5]
	_ = x[NationalityBahraini-6]
	_ = x[NationalityBelgian-7]
	_ = x[NationalityBolivian-8]
	_ = x[NationalityBrazilian-9]
	_ = x[NationalityBritish-10]
	_ = x[NationalityBulgarian-11]
	_ = x[NationalityCameroonian-12]
	_ = x[NationalityCanadian-13]
	_ = x[NationalityChilean-14]
	_ = x[NationalityChinese-15]
	_ = x[NationalityColombian-16]
	_ = x[NationalityCostaRican-17]
	_ = x[NationalityCroatian-18]
	_ = x[NationalityCypriot-19]
	_ = x[NationalityCzech-20]
	_ = x[NationalityDanish-21]
	_ = x[NationalityDutch-22]
	_ = x[NationalityEcuadorian-23]
	_ = x[NationalityEnglish-24]
	_ = x[NationalityEmirian-25]
	_ = x[NationalityEstonian-26]
	_ = x[NationalityFinnish-27]
	_ = x[NationalityGreek-28]
	_ = x[NationalityGuatemalan-29]
	_ = x[NationalityHonduran-30]
	_ = x[NationalityHongKonger-31]
	_ = x[NationalityHungarian-32]
	_ = x[NationalityIcelander-33]
	_ = x[NationalityIndian-34]
	_ = x[NationalityIndonesian-35]
	_ = x[NationalityIrish-36]
	_ = x[NationalityIsraeli-37]
	_ = x[NationalityItalian-38]
	_ = x[NationalityJamaican-39]
	_ = x[NationalityJapanese-40]
	_ = x[NationalityJordanian-41]
	_ = x[NationalityKuwaiti-42]
	_ = x[NationalityLatvian-43]
	_ = x[NationalityLebanese-44]
	_ = x[NationalityLithuanian-45]
	_ = x[NationalityLuxembourger-46]
	_ = x[NationalityMalaysian-47]
	_ = x[NationalityMaltese-48]
	_ = x[NationalityMexican-49]
	_ = x[NationalityMonegasque-50]
	_ = x[NationalityNewZealander-51]
	_ = x[NationalityNicaraguan-52]
	_ = x[NationalityNorthernIrish-53]
	_ = x[NationalityNorwegian-54]
	_ = x[NationalityParaguayan-55]
	_ = x[NationalityPeruvian-56]
	_ = x[NationalityPolish-57]
	_ = x[NationalityPortuguese-58]
	_ = x[NationalityQatari-59]
	_ = x[NationalityRomanian-60]
	_ = x[NationalityRussian-61]
	_ = x[NationalitySalvadoran-62]
	_ = x[NationalitySaudi-63]
	_ = x[NationalityScottish-64]
	_ = x[NationalitySerbian-65]
	_ = x[NationalitySingaporean-66]
	_ = x[NationalitySlovakian-67]
	_ = x[NationalitySlovenian-68]
	_ = x[NationalitySouthKorean-69]
	_ = x[NationalitySouthAfrican-70]
	_ = x[NationalitySpanish-71]
	_ = x[NationalitySwedish-72]
	_ = x[NationalitySwiss-73]
	_ = x[NationalityThai-74]
	_ = x[NationalityTurkish-75]
	_ = x[NationalityUruguayan-76]
	_ = x[NationalityUkrainian-77]
	_ = x[NationalityVenezuelan-78]
	_ = x[NationalityBarbadian-79]
	_ = x[NationalityWelsh-80]
	_ = x[NationalityVietnamese-81]
}

const _Nationality_name = "NationalityUnknownNationalityAmericanNationalityArgentineanNationalityAustralianNationalityAustrianNationalityAzerbaijaniNationalityBahrainiNationalityBelgianNationalityBolivianNationalityBrazilianNationalityBritishNationalityBulgarianNationalityCameroonianNationalityCanadianNationalityChileanNationalityChineseNationalityColombianNationalityCostaRicanNationalityCroatianNationalityCypriotNationalityCzechNationalityDanishNationalityDutchNationalityEcuadorianNationalityEnglishNationalityEmirianNationalityEstonianNationalityFinnishNationalityGreekNationalityGuatemalanNationalityHonduranNationalityHongKongerNationalityHungarianNationalityIcelanderNationalityIndianNationalityIndonesianNationalityIrishNationalityIsraeliNationalityItalianNationalityJamaicanNationalityJapaneseNationalityJordanianNationalityKuwaitiNationalityLatvianNationalityLebaneseNationalityLithuanianNationalityLuxembourgerNationalityMalaysianNationalityMalteseNationalityMexicanNationalityMonegasqueNationalityNewZealanderNationalityNicaraguanNationalityNorthernIrishNationalityNorwegianNationalityParaguayanNationalityPeruvianNationalityPolishNationalityPortugueseNationalityQatariNationalityRomanianNationalityRussianNationalitySalvadoranNationalitySaudiNationalityScottishNationalitySerbianNationalitySingaporeanNationalitySlovakianNationalitySlovenianNationalitySouthKoreanNationalitySouthAfricanNationalitySpanishNationalitySwedishNationalitySwissNationalityThaiNationalityTurkishNationalityUruguayanNationalityUkrainianNationalityVenezuelanNationalityBarbadianNationalityWelshNationalityVietnamese"

var _Nationality_index = [...]uint16{0, 18, 37, 59, 80, 99, 121, 140, 158, 177, 197, 215, 235, 257, 276, 294, 312, 332, 353, 372, 390, 406, 423, 439, 460, 478, 496, 515, 533, 549, 570, 589, 610, 630, 650, 667, 688, 704, 722, 740, 759, 778, 798, 816, 834, 853, 874, 897, 917, 935, 953, 974, 997, 1018, 1042, 1062, 1083, 1102, 1119, 1140, 1157, 1176, 1194, 1215, 1231, 1250, 1268, 1290, 1310, 1330, 1352, 1375, 1393, 1411, 1427, 1442, 1460, 1480, 1500, 1521, 1541, 1557, 1578}

func (i Nationality) String() string {
	if i >= Nationality(len(_Nationality_index)-1) {
		return "Nationality(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Nationality_name[_Nationality_index[i]:_Nationality_index[i+1]]
}
