// Code generated by "stringer -type=PacketID"; DO NOT EDIT.

package f12021

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PacketIDMotion-0]
	_ = x[PacketIDSession-1]
	_ = x[PacketIDLapData-2]
	_ = x[PacketIDEvent-3]
	_ = x[PacketIDParticipants-4]
	_ = x[PacketIDCarSetups-5]
	_ = x[PacketIDCarTelemetry-6]
	_ = x[PacketIDCarStatus-7]
	_ = x[PacketIDFinalClassification-8]
	_ = x[PacketIDLobbyInfo-9]
	_ = x[PacketIDCarDamage-10]
	_ = x[PacketIDSessionHistory-11]
}

const _PacketID_name = "PacketIDMotionPacketIDSessionPacketIDLapDataPacketIDEventPacketIDParticipantsPacketIDCarSetupsPacketIDCarTelemetryPacketIDCarStatusPacketIDFinalClassificationPacketIDLobbyInfoPacketIDCarDamagePacketIDSessionHistory"

var _PacketID_index = [...]uint8{0, 14, 29, 44, 57, 77, 94, 114, 131, 158, 175, 192, 214}

func (i PacketID) String() string {
	if i >= PacketID(len(_PacketID_index)-1) {
		return "PacketID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketID_name[_PacketID_index[i]:_PacketID_index[i+1]]
}
