// Code generated by "stringer -type=SessionType"; DO NOT EDIT.

package f12021

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SessionTypeUnknown-0]
	_ = x[SessionTypePractice1-1]
	_ = x[SessionTypePractice2-2]
	_ = x[SessionTypePractice3-3]
	_ = x[SessionTypeShortPractice-4]
	_ = x[SessionTypeQualifying1-5]
	_ = x[SessionTypeQualifying2-6]
	_ = x[SessionTypeQualifying3-7]
	_ = x[SessionTypeShortQualifying-8]
	_ = x[SessionTypeOneShotQualifying-9]
	_ = x[SessionTypeRace-10]
	_ = x[SessionTypeRace2-11]
	_ = x[SessionTypeRace3-12]
	_ = x[SessionTypeTimeTrial-13]
}

const _SessionType_name = "SessionTypeUnknownSessionTypePractice1SessionTypePractice2SessionTypePractice3SessionTypeShortPracticeSessionTypeQualifying1SessionTypeQualifying2SessionTypeQualifying3SessionTypeShortQualifyingSessionTypeOneShotQualifyingSessionTypeRaceSessionTypeRace2SessionTypeRace3SessionTypeTimeTrial"

var _SessionType_index = [...]uint16{0, 18, 38, 58, 78, 102, 124, 146, 168, 194, 222, 237, 253, 269, 289}

func (i SessionType) String() string {
	if i >= SessionType(len(_SessionType_index)-1) {
		return "SessionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SessionType_name[_SessionType_index[i]:_SessionType_index[i+1]]
}
