// Code generated by "stringer -type=SessionType -trimprefix=SessionType"; DO NOT EDIT.

package f12021

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SessionTypeUnknown-0]
	_ = x[SessionTypePractice1-1]
	_ = x[SessionTypePractice2-2]
	_ = x[SessionTypePractice3-3]
	_ = x[SessionTypeShortPractice-4]
	_ = x[SessionTypeQualifying1-5]
	_ = x[SessionTypeQualifying2-6]
	_ = x[SessionTypeQualifying3-7]
	_ = x[SessionTypeShortQualifying-8]
	_ = x[SessionTypeOneShotQualifying-9]
	_ = x[SessionTypeRace-10]
	_ = x[SessionTypeRace2-11]
	_ = x[SessionTypeRace3-12]
	_ = x[SessionTypeTimeTrial-13]
}

const _SessionType_name = "UnknownPractice1Practice2Practice3ShortPracticeQualifying1Qualifying2Qualifying3ShortQualifyingOneShotQualifyingRaceRace2Race3TimeTrial"

var _SessionType_index = [...]uint8{0, 7, 16, 25, 34, 47, 58, 69, 80, 95, 112, 116, 121, 126, 135}

func (i SessionType) String() string {
	if i >= SessionType(len(_SessionType_index)-1) {
		return "SessionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SessionType_name[_SessionType_index[i]:_SessionType_index[i+1]]
}
