// Code generated by "stringer -type=Team"; DO NOT EDIT.

package f12021

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TeamMercedes-0]
	_ = x[TeamFerrari-1]
	_ = x[TeamRedBullRacing-2]
	_ = x[TeamWilliams-3]
	_ = x[TeamAstonMartin-4]
	_ = x[TeamAlipne-5]
	_ = x[TeamAlphaTauri-6]
	_ = x[TeamHaas-7]
	_ = x[TeamMcLaren-8]
	_ = x[TeamAlfaRomeo-9]
	_ = x[TeamArtGP2019-42]
	_ = x[TeamCampos2019-43]
	_ = x[TreamCarlin2019-44]
	_ = x[TeamSauberJuniorCharouz2019-45]
	_ = x[TeamDams2019-46]
	_ = x[TeamUniVirtuosi2019-47]
	_ = x[TeamMPMotorsport2019-48]
	_ = x[TeamPrema2019-49]
	_ = x[TeamTrident2019-50]
	_ = x[TeamArden2019-51]
	_ = x[TeamArtGP2020-70]
	_ = x[TeamCampos2020-71]
	_ = x[TreamCarlin2020-72]
	_ = x[TeamCharouz2020-73]
	_ = x[TeamDams2020-74]
	_ = x[TeamUniVirtuosi2020-75]
	_ = x[TeamMPMotorsport2020-76]
	_ = x[TeamPrema2020-77]
	_ = x[TeamTrident2020-78]
	_ = x[TeamBWT2020-79]
	_ = x[TeamHitech2020-80]
	_ = x[TeamMercedes2020-85]
	_ = x[TeamFerrari2020-86]
	_ = x[TeamRedBull2020-87]
	_ = x[TeamWilliams2020-88]
	_ = x[TeamRacingPoint2020-89]
	_ = x[TeamRenault2020-90]
	_ = x[TeamAlphaTauri2020-91]
	_ = x[TeamHaas2020-92]
	_ = x[TeamMcLaren2020-93]
	_ = x[TeamAlfaRomeo2020-94]
}

const (
	_Team_name_0 = "TeamMercedesTeamFerrariTeamRedBullRacingTeamWilliamsTeamAstonMartinTeamAlipneTeamAlphaTauriTeamHaasTeamMcLarenTeamAlfaRomeo"
	_Team_name_1 = "TeamArtGP2019TeamCampos2019TreamCarlin2019TeamSauberJuniorCharouz2019TeamDams2019TeamUniVirtuosi2019TeamMPMotorsport2019TeamPrema2019TeamTrident2019TeamArden2019"
	_Team_name_2 = "TeamArtGP2020TeamCampos2020TreamCarlin2020TeamCharouz2020TeamDams2020TeamUniVirtuosi2020TeamMPMotorsport2020TeamPrema2020TeamTrident2020TeamBWT2020TeamHitech2020"
	_Team_name_3 = "TeamMercedes2020TeamFerrari2020TeamRedBull2020TeamWilliams2020TeamRacingPoint2020TeamRenault2020TeamAlphaTauri2020TeamHaas2020TeamMcLaren2020TeamAlfaRomeo2020"
)

var (
	_Team_index_0 = [...]uint8{0, 12, 23, 40, 52, 67, 77, 91, 99, 110, 123}
	_Team_index_1 = [...]uint8{0, 13, 27, 42, 69, 81, 100, 120, 133, 148, 161}
	_Team_index_2 = [...]uint8{0, 13, 27, 42, 57, 69, 88, 108, 121, 136, 147, 161}
	_Team_index_3 = [...]uint8{0, 16, 31, 46, 62, 81, 96, 114, 126, 141, 158}
)

func (i Team) String() string {
	switch {
	case i <= 9:
		return _Team_name_0[_Team_index_0[i]:_Team_index_0[i+1]]
	case 42 <= i && i <= 51:
		i -= 42
		return _Team_name_1[_Team_index_1[i]:_Team_index_1[i+1]]
	case 70 <= i && i <= 80:
		i -= 70
		return _Team_name_2[_Team_index_2[i]:_Team_index_2[i+1]]
	case 85 <= i && i <= 94:
		i -= 85
		return _Team_name_3[_Team_index_3[i]:_Team_index_3[i+1]]
	default:
		return "Team(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
