// Code generated by "stringer -type=Track -trimprefix=Track"; DO NOT EDIT.

package f12021

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TrackUnknown - -1]
	_ = x[TrackMelbourne-0]
	_ = x[TrackPaulRicard-1]
	_ = x[TrackShanghai-2]
	_ = x[TrackSakhir-3]
	_ = x[TrackCatalunya-4]
	_ = x[TrackMonaco-5]
	_ = x[TrackMontreal-6]
	_ = x[TrackSilverstone-7]
	_ = x[TrackHockenheim-8]
	_ = x[TrackHungaroring-9]
	_ = x[TrackSpa-10]
	_ = x[TrackMonza-11]
	_ = x[TrackSingapore-12]
	_ = x[TrackSuzuka-13]
	_ = x[TrackAbuDhabi-14]
	_ = x[TrackTexas-15]
	_ = x[TrackBrazil-16]
	_ = x[TrackAustria-17]
	_ = x[TrackSochi-18]
	_ = x[TrackMexico-19]
	_ = x[TrackBaku-20]
	_ = x[TrackSakhirShort-21]
	_ = x[TrackSilverstoneShort-22]
	_ = x[TrackTexasShort-23]
	_ = x[TrackSuzukaShort-24]
	_ = x[TrackHanoi-25]
	_ = x[TrackZandvoort-26]
	_ = x[TrackImola-27]
	_ = x[TrackPortimão-28]
	_ = x[TrackJeddah-29]
}

const _Track_name = "UnknownMelbournePaulRicardShanghaiSakhirCatalunyaMonacoMontrealSilverstoneHockenheimHungaroringSpaMonzaSingaporeSuzukaAbuDhabiTexasBrazilAustriaSochiMexicoBakuSakhirShortSilverstoneShortTexasShortSuzukaShortHanoiZandvoortImolaPortimãoJeddah"

var _Track_index = [...]uint8{0, 7, 16, 26, 34, 40, 49, 55, 63, 74, 84, 95, 98, 103, 112, 118, 126, 131, 137, 144, 149, 155, 159, 170, 186, 196, 207, 212, 221, 226, 235, 241}

func (i Track) String() string {
	i -= -1
	if i < 0 || i >= Track(len(_Track_index)-1) {
		return "Track(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Track_name[_Track_index[i]:_Track_index[i+1]]
}
