// Code generated by "stringer -type=TyreCompound"; DO NOT EDIT.

package f12021

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TyreCompoundFormula1ModernC5-16]
	_ = x[TyreCompoundFormula1ModernC4-17]
	_ = x[TyreCompoundFormula1ModernC3-18]
	_ = x[TyreCompoundFormula1ModernC2-19]
	_ = x[TyreCompoundFormula1ModernC1-20]
	_ = x[TyreCompoundFormula1ModernInter-7]
	_ = x[TyreCompoundFormula1ModernWet-8]
	_ = x[TyreCompoundFormula1ClassicDry-9]
	_ = x[TyreCompoundFormula1ClassicWet-10]
	_ = x[TyreCompoundFormula2SuperSoft-11]
	_ = x[TyreCompoundFormula2Soft-12]
	_ = x[TyreCompoundFormula2Medium-13]
	_ = x[TyreCompoundFormula2Hard-14]
	_ = x[TyreCompoundFormula2Wet-15]
}

const _TyreCompound_name = "TyreCompoundFormula1ModernInterTyreCompoundFormula1ModernWetTyreCompoundFormula1ClassicDryTyreCompoundFormula1ClassicWetTyreCompoundFormula2SuperSoftTyreCompoundFormula2SoftTyreCompoundFormula2MediumTyreCompoundFormula2HardTyreCompoundFormula2WetTyreCompoundFormula1ModernC5TyreCompoundFormula1ModernC4TyreCompoundFormula1ModernC3TyreCompoundFormula1ModernC2TyreCompoundFormula1ModernC1"

var _TyreCompound_index = [...]uint16{0, 31, 60, 90, 120, 149, 173, 199, 223, 246, 274, 302, 330, 358, 386}

func (i TyreCompound) String() string {
	i -= 7
	if i >= TyreCompound(len(_TyreCompound_index)-1) {
		return "TyreCompound(" + strconv.FormatInt(int64(i+7), 10) + ")"
	}
	return _TyreCompound_name[_TyreCompound_index[i]:_TyreCompound_index[i+1]]
}
