// Code generated by "stringer -type=VisualTyreCompound"; DO NOT EDIT.

package f12021

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VisualTyreCompoundFormula1ModernSoft-16]
	_ = x[VisualTyreCompoundFormula1ModernMedium-17]
	_ = x[VisualTyreCompoundFormula1ModernHard-18]
	_ = x[VisualTyreCompoundFormula1ModernInter-7]
	_ = x[VisualTyreCompoundFormula1ModernWet-8]
	_ = x[VisualTyreCompoundFormula1ClassicSoft-16]
	_ = x[VisualTyreCompoundFormula1ClassicMedium-17]
	_ = x[VisualTyreCompoundFormula1ClassicHard-18]
	_ = x[VisualTyreCompoundFormula1ClassicInter-7]
	_ = x[VisualTyreCompoundFormula1ClassicWet-8]
	_ = x[VisualTyreCompoundFormula2Wet-15]
	_ = x[VisualTyreCompoundFormula2SuperSoft-19]
	_ = x[VisualTyreCompoundFormula2Soft-20]
	_ = x[VisualTyreCompoundFormula2Medium-21]
	_ = x[VisualTyreCompoundFormula2Hard-22]
}

const (
	_VisualTyreCompound_name_0 = "VisualTyreCompoundFormula1ModernInterVisualTyreCompoundFormula1ModernWet"
	_VisualTyreCompound_name_1 = "VisualTyreCompoundFormula2WetVisualTyreCompoundFormula1ModernSoftVisualTyreCompoundFormula1ModernMediumVisualTyreCompoundFormula1ModernHardVisualTyreCompoundFormula2SuperSoftVisualTyreCompoundFormula2SoftVisualTyreCompoundFormula2MediumVisualTyreCompoundFormula2Hard"
)

var (
	_VisualTyreCompound_index_0 = [...]uint8{0, 37, 72}
	_VisualTyreCompound_index_1 = [...]uint16{0, 29, 65, 103, 139, 174, 204, 236, 266}
)

func (i VisualTyreCompound) String() string {
	switch {
	case 7 <= i && i <= 8:
		i -= 7
		return _VisualTyreCompound_name_0[_VisualTyreCompound_index_0[i]:_VisualTyreCompound_index_0[i+1]]
	case 15 <= i && i <= 22:
		i -= 15
		return _VisualTyreCompound_name_1[_VisualTyreCompound_index_1[i]:_VisualTyreCompound_index_1[i+1]]
	default:
		return "VisualTyreCompound(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
