// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetItem(arg1:string):Promise<any>;

export function RemoveItem(arg1:string):void;

export function SetItem(arg1:string,arg2:string):void;
