// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetItem(arg1) {
  return window['go']['app']['App']['GetItem'](arg1);
}

export function RemoveItem(arg1) {
  window['go']['app']['App']['RemoveItem'](arg1);
}

export function SetItem(arg1, arg2) {
  window['go']['app']['App']['SetItem'](arg1, arg2);
}
